[package]
name = "nimiq-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Primitives (e.g., block, account, transaction) to be used in Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
num-bigint = { version = "0.2", optional = true }
num-traits = { version = "0.2", optional = true }
parking_lot = { version = "0.7", optional = true }
hex = { version = "0.3", optional = true }
lazy_static = { version = "1.2", optional = true }
failure = { version = "0.1", optional = true}
enum-display-derive = { version = "0.1", optional = true }
beserial = { path = "../beserial", version = "0.1" }
beserial_derive = { path = "../beserial/beserial_derive", version = "0.1" }
nimiq-macros = { path = "../macros", version = "0.1", optional = true }
fixed-unsigned = { path = "../fixed-unsigned", version = "0.1", optional = true }

[dev-dependencies]
lazy_static = "1.2"

[features]
default = ["all"]
all = ["coin", "account", "policy", "networks"]
coin = ["hex", "failure"]
account = ["hex", "nimiq-macros", "failure", "enum-display-derive"]
policy = ["num-bigint", "num-traits", "parking_lot", "lazy_static", "fixed-unsigned"]
networks = []
