[package]
name = "beserial_derive"
version = "0.1.0"
authors = ["Marvin W <git@larma.de>"]
edition = "2018"
description = "Derive macros for beserial"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain", "serialization"]

[badges]
gitlab = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "https://github.com/nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "https://github.com/nimiq/core-rs" }
maintenance = { status = "experimental" }

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
syn = "0.15"
quote = "0.6"
beserial = { path = "..", version = "0.1" }
