[package]
name = "nimiq-tree-primitives"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Accounts tree primitives for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
hex = "0.3"
beserial = { path = "../../beserial", version = "0.1" }
beserial_derive = { path = "../../beserial/beserial_derive", version = "0.1" }
nimiq-keys = { path = "../../keys", version = "0.1" }
nimiq-hash = { path = "../../hash", version = "0.1" }
nimiq-account = { path = "../../primitives/account", version = "0.1" }

[dev-dependencies]
nimiq-primitives = { path = "../../primitives", version = "0.1", features = ["coin"] }
