[package]
name = "nimiq-database"
version = "0.1.0"
authors = ["Pascal B <git@paberr.net>", "The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "A LMDB database wrapper with support for volatile storage"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
gitlab = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "https://github.com/nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "https://github.com/nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
log = "0.4"
lmdb-zero = "0.4"
fs2 = "0.4"
parking_lot = "0.7"
tempdir = "0.3"
rand = "0.6"
bitflags = "1.0"
beserial = { path = "../beserial", version = "0.1" }
nimiq-hash = { path = "../hash", version = "0.1", optional = true }
nimiq-keys = { path = "../keys", version = "0.1", optional = true }
nimiq-block = { path = "../primitives/block", version = "0.1", optional = true }
nimiq-tree-primitives = { path = "../accounts/tree-primitives", version = "0.1", optional = true }

[features]
# Compiles this package with all features needed for the nimiq client.
full-nimiq = ["hash", "block", "account", "keys"]
hash = ["nimiq-hash"]
block = ["nimiq-block"]
account = ["nimiq-tree-primitives"]
keys = ["nimiq-keys"]
