[package]
name = "nimiq-metrics-server"
version = "0.2.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
edition = "2018"
description = "Prometheus metrics server for the Nimiq Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
hyper = "0.12"
futures = "0.1"
log = "0.4"
base64 = "0.10"
failure = "0.1"
nimiq-blockchain = { path = "../blockchain", version = "0.2", features = ["metrics"] }
nimiq-consensus = { path = "../consensus", version = "0.2" }
nimiq-network = { path = "../network", version = "0.2", features = ["metrics"] }
nimiq-mempool = { path = "../mempool", version = "0.2" }
nimiq-block = { path = "../primitives/block", version = "0.2" }
beserial = { path = "../beserial", version = "0.2" }
