[package]
name = "nimiq-utils"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Various utilities (e.g., CRC, Merkle proofs, timers) for Nimiq's Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
gitlab = { repository = "nimiq/core-rs", branch = "master" }
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
bit-vec = { version = "0.5", optional = true }
futures = { version = "0.1", optional = true }
parking_lot = { version = "0.7", optional = true }
tokio = { version = "0.1", optional = true }
log = { version = "0.4", optional = true }
nimiq-hash = { path = "../hash", version = "0.1", optional = true }
beserial = { path = "../beserial", version = "0.1", optional = true }
nimiq-collections = { path = "../collections", version = "0.1", optional = true }

[features]
crc = []
iterators = []
locking = ["futures", "parking_lot"]
merkle = ["beserial", "nimiq-hash", "bit-vec"]
mutable-once = []
observer = []
time = []
timers = ["futures", "parking_lot", "tokio", "log"]
unique-ptr = []
throttled-queue = ["nimiq-collections"]
rate-limit = []
unique-id = []
# Compiles this package with all features.
all = ["bit-vec", "crc", "iterators", "locking", "merkle", "mutable-once", "observer", "time", "timers", "unique-ptr", "throttled-queue", "rate-limit", "unique-id"]
# Compiles this package with the features needed for the nimiq client.
full-nimiq = ["crc", "iterators", "locking", "merkle", "mutable-once", "observer", "time", "timers", "unique-ptr"]