[package]
name = "nimiq-consensus"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Consensus implementation of Nimiq in Rust"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
gitlab = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "https://github.com/nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "https://github.com/nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
parking_lot = "0.7"
rand = "0.6"
log = "0.4"
weak-table = "0.2"
failure = "0.1"
futures = "0.1"
tokio = "0.1"
beserial = { path = "../beserial", version = "0.1" }
nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-macros = { path = "../macros", version = "0.1" }
nimiq-block = { path = "../primitives/block", version = "0.1" }
nimiq-transaction = { path = "../primitives/transaction", version = "0.1" }
nimiq-mempool = { path = "../mempool", version = "0.1" }
nimiq-collections = { path = "../collections", version = "0.1" }
nimiq-messages = { path = "../messages", version = "0.1" }
nimiq-network-primitives = { path = "../network-primitives", version = "0.1", features = ["networks", "time"] }
nimiq-network = { path = "../network", version = "0.1" }
nimiq-database = { path = "../database", version = "0.1", features = ["full-nimiq"] }
nimiq-utils = { path = "../utils", version = "0.1", features = ["observer", "timers", "mutable-once", "throttled-queue", "rate-limit"] }
nimiq-blockchain = { path = "../blockchain", version = "0.1", features = ["transaction-store"] }
